FROM openjdk:14-jdk-alpine as MAVEN_BUILD

LABEL key="riot90" 

ARG WORKDIR="/build/"

WORKDIR ${WORKDIR}
COPY ./ ${WORKDIR}/

RUN ./mvnw clean package

FROM openjdk:14-jdk-alpine

WORKDIR ${WORKDIR}
COPY --from=MAVEN_BUILD ${WORKDIR}/target/*.jar ${WORKDIR}/app.jar

CMD ["java", "-jar", "app.jar"]